// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingLot1._0.Persistence.Contexts;

#nullable disable

namespace ParkingLot1._0.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.MonthlyPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RateId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MonthlyPasses");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.ParkingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<int?>("RateId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("RateId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingRecords");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MonthlyPassId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkingRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyPassId");

                    b.HasIndex("ParkingRecordId")
                        .IsUnique()
                        .HasFilter("[ParkingRecordId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.MonthlyPass", b =>
                {
                    b.HasOne("ParkingLot1._0.Domain.Entities.Customer", "Customer")
                        .WithMany("MonthlyPasses")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("ParkingLot1._0.Domain.Entities.Rate", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId")
                        .IsRequired();

                    b.HasOne("ParkingLot1._0.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Rate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.ParkingRecord", b =>
                {
                    b.HasOne("ParkingLot1._0.Domain.Entities.Employee", "Employee")
                        .WithMany("ParkingRecords")
                        .HasForeignKey("EmployeeId")
                        .IsRequired();

                    b.HasOne("ParkingLot1._0.Domain.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("ParkingRecords")
                        .HasForeignKey("ParkingSpotId")
                        .IsRequired();

                    b.HasOne("ParkingLot1._0.Domain.Entities.Rate", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId");

                    b.HasOne("ParkingLot1._0.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingRecords")
                        .HasForeignKey("VehicleId")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ParkingSpot");

                    b.Navigation("Rate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ParkingLot1._0.Domain.Entities.MonthlyPass", "MonthlyPass")
                        .WithMany()
                        .HasForeignKey("MonthlyPassId");

                    b.HasOne("ParkingLot1._0.Domain.Entities.ParkingRecord", "ParkingRecord")
                        .WithOne("Payment")
                        .HasForeignKey("ParkingLot1._0.Domain.Entities.Payment", "ParkingRecordId");

                    b.Navigation("MonthlyPass");

                    b.Navigation("ParkingRecord");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("ParkingLot1._0.Domain.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Customer", b =>
                {
                    b.Navigation("MonthlyPasses");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ParkingRecords");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.ParkingRecord", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.ParkingSpot", b =>
                {
                    b.Navigation("ParkingRecords");
                });

            modelBuilder.Entity("ParkingLot1._0.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
